/* -*- c-basic-offset: 4; indent-tabs-mode: nil; tab-width: 4 -*- */
/* vi: set ts=4 sw=4 expandtab: (add to ~/.vimrc: set modeline modelines=5) */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* used by redtamarin.py to build redtamarin.abc */

/* builtins */

/* note:
   we cannot include the builtins here for the following reasons
   - conflict of namespaces
   - this file is used by both shell_toplevel.py and redtamarin.py
   - in shell_toplevel.py we don't compile builtins, we reuse builtins.abc
   - in redtamarin.py we do compile and merge the buildins into redtamarin.abc
*/

/* versioning notes:
   by default versioning files are autogenerated
   in AS3 you get core/api-versions.as
   defining
   CONFIG const AIR_1_0 = 661;
   CONFIG const FP_10_0 = 662;
   CONFIG const AIR_1_5 = 663;
   etc.

   and is used in builtins
   and was used for shell_toplevel

   but in our case as we want to build all from a single script
   we need to declare those const outside of CONFIG
   AVMGLUE const AIR_1_0 = 661;
   AVMGLUE const FP_10_0 = 662;
   AVMGLUE const AIR_1_5 = 663;
   etc.

   we decided to use the namespace AVMGLUE
   that way builtins stay unmodified which we thin kis best
   and we can structure our shell_toplevel/redtamarin scripts
   the way we want and withoiut conflicts

   for now, we need to sync as3/versioning.as by hand
   later, we will provide a script or modify utils/apivergen.as
*/

include "as3/versioning.as";

include "as3/AVM2.as";

/* C standard library for AS3 */

include "as3/C/ISO_C.as";
include "as3/C/assert.as"; //not implemented
include "as3/C/ctype.as";
include "as3/C/errno.as";
//C.float -- not supported
include "as3/C/limits.as";
include "as3/C/locale.as";
include "as3/C/math.as";
//C.setjmp -- not supported
include "as3/C/signal.as";
//C.stdarg -- not supported
//C.stddef -- not supported
include "as3/C/stdio.as";
include "as3/C/stdlib.as";
include "as3/C/string.as";
include "as3/C/time.as";

include "as3/C/POSIX.as";
include "as3/C/conio.as";
include "as3/C/cpio.as";
include "as3/C/dirent.as";
include "as3/C/fcntl.as";
//C.grp
include "as3/C/netdb.as";
include "as3/C/netinet.as";
//C.pthread
//C.pwd
include "as3/C/spawn.as";
//C.sys.ipc
//C.sys.mman
//C.sys.msg
//C.sys.sem
include "as3/C/sys/socket.as";
include "as3/C/sys/stat.as";
//C.sys.time
//C.sys.types
//C.sys.utsname
include "as3/C/sys/wait.as";
//C.tar
//C.termios
include "as3/C/unistd.as";
//C.utime

//include "as3/C/socket.as"; //deprecated


/* redtamarin native library */

include "as3/shell/Program.as";
include "as3/shell/Runtime.as";
include "as3/shell/Diagnostics.as";
include "as3/shell/HardwareInformation.as";
include "as3/shell/OperatingSystem.as";
include "as3/shell/RunMode.as";
include "as3/shell/Domain.as";
include "as3/shell/FileIO.as";
include "as3/shell/Environment.as";
include "as3/shell/BinaryData.as";
include "as3/shell/async/EventLoop.as";
/* alpha */ include "as3/shell/async/CoreEventLoop.as";

//globals
include "as3/getClassByName.as";
include "as3/print.as";
include "as3/trace.as";
include "as3/getTimer.as";
include "as3/readLine.as";

//redtamarin boot sequence
include "as3/shell/boot.as";

/* avmglue library */

/* note:
   here what defines the FPAPI (Flash Platform API)

   we support compatibility for:
   - Flash Player API v9+
   - AIR API v1+
   - versioning
*/

//-- toplevel/global --
//AS3 namespace -- defined in builtin.as

//NaN -- defined in builtin.as
//Infinity -- defined in builtin.as
//undefined -- defined in builtin.as

//bugzilla() -- defined in builtin.as - not part of the FPAPI
//decodeURI() -- defined in builtin.as
//decodeURIComponent() -- defined in builtin.as
//encodeURI() -- defined in builtin.as
//encodeURIComponent() -- defined in builtin.as
//isNaN() -- defined in builtin.as
//isFinite() -- defined in builtin.as
//parseInt() -- defined in builtin.as
//parseFloat() -- defined in builtin.as
//escape() -- defined in builtin.as
//unescape() -- defined in builtin.as
//isXMLName() -- defined in builtin.as
//trace() -- defined in globals above

//Object -- defined in builtin.as
//Class -- defined in builtin.as
//Function -- defined in builtin.as
//MethodClosure -- defined in builtin.as
//Namespace -- defined in builtin.as
//Boolean -- defined in builtin.as
//Number -- defined in builtin.as
//int -- defined in builtin.as
//uint -- defined in builtin.as
//float -- defined in builtin.as - depends on compilation config
//float4 -- defined in builtin.as - depends on compilation config
//String -- defined in builtin.as
//Array -- defined in builtin.as
//Vector -- defined in builtin.as -- depends on versioning
//Math -- defined in Math.as
//Error -- defined in Error.as
//DefinitionError -- defined in Error.as
//EvalError -- defined in Error.as
//RangeError -- defined in Error.as
//ReferenceError -- defined in Error.as
//SecurityError -- defined in Error.as
//SyntaxError -- defined in Error.as
//TypeError -- defined in Error.as
//URIError -- defined in Error.as
//VerifyError -- defined in Error.as
//UninitializedError -- defined in Error.as
//ArgumentError -- defined in Error.as
//Date -- defined in Date.as
//RegExp -- defined in RegExp.as
//JSON -- defined in JSON.as
//XML -- defined in XML.as
//XMLList -- defined in XML.as
//QName -- defined in XML.as


//-- avm2.intrinsics.memory --
//avm2.intrinsics.memory.mfence() -- defined in concurrent.as
//avm2.intrinsics.memory.casi32() -- defined in concurrent.as


//-- avmplus --
//avmplus.HIDE_NSURI_METHODS -- defined in builtin.as
//avmplus.INCLUDE_BASES -- defined in builtin.as
//avmplus.INCLUDE_INTERFACES -- defined in builtin.as
//avmplus.INCLUDE_VARIABLES -- defined in builtin.as
//avmplus.INCLUDE_ACCESSORS -- defined in builtin.as
//avmplus.INCLUDE_METHODS -- defined in builtin.as
//avmplus.INCLUDE_METADATA -- defined in builtin.as
//avmplus.INCLUDE_TRAITS -- defined in builtin.as
//avmplus.USE_ITRAITS -- defined in builtin.as
//avmplus.HIDE_OBJECT -- defined in builtin.as
//avmplus.FLASH10_FLAGS -- defined in builtin.as
//avmplus.describeType() -- defined in builtin.as
//avmplus.getQualifiedClassName() -- defined in builtin.as
//avmplus.getQualifiedSuperclassName() -- defined in builtin.as


//-- adobe.utils --
//MMEndCommand()
//MMExecute()

//CustomActions
//XMLUI


//-- air.desktop --
//URLFilePromise


//-- air.net --
//SecureSocketMonitor
//ServiceMonitor
//SocketMonitor
//URLMonitor

//-- air.update --
//ApplicationUpdater
//ApplicationUpdaterUI


//-- air.update.events --
//DownloadErrorEvent
//StatusFileUpdateErrorEvent
//StatusFileUpdateEvent
//StatusUpdateErrorEvent
//StatusUpdateEvent
//UpdateEvent


//-- com.adobe.viewsource --
//ViewSource



//-- flash.accessibility --
include "as3/flash/accessibility/ISearchableText.as";
include "as3/flash/accessibility/ISimpleTextSelection.as";

include "as3/flash/accessibility/Accessibility.as";
include "as3/flash/accessibility/AccessibilityImplementation.as";
include "as3/flash/accessibility/AccessibilityProperties.as";


//-- flash.concurrent --
//flash.concurrent.Mutex -- defined in concurrent.as
//flash.concurrent.Condition -- defined in concurrent.as


//-- flash.crypto --
include "as3/flash/crypto/generateRandomBytes.as";


//-- flash.data --
include "as3/flash/data/EncryptedLocalStore.as";
include "as3/flash/data/SQLCollationType.as";
include "as3/flash/data/SQLColumnNameStyle.as";
include "as3/flash/data/SQLColumnSchema.as";
include "as3/flash/data/SQLConnection.as";
include "as3/flash/data/SQLIndexSchema.as";
include "as3/flash/data/SQLMode.as";
include "as3/flash/data/SQLResult.as";
include "as3/flash/data/SQLSchema.as";
include "as3/flash/data/SQLSchemaResult.as";
include "as3/flash/data/SQLStatement.as";
include "as3/flash/data/SQLTableSchema.as";
include "as3/flash/data/SQLTransactionLockType.as";
include "as3/flash/data/SQLTriggerSchema.as";
include "as3/flash/data/SQLViewSchema.as";


//-- flash.debugger --
include "as3/flash/debugger/enterDebugger.as";


//-- flash.desktop --
//IFilePromise

//Clipboard
//ClipboardFormats
//ClipboardTransferMode
//DockIcon
//Icon
//InteractiveIcon
//InvokeEventReason
//NativeApplication
//NativeDragActions
//NativeDragManager
//NativeDragOptions
//NativeProcess
//NativeProcessStartupInfo
//NotificationType
//SystemIdleMode
//SystemTrayIcon
//Updater

//-- flash.display --
include "as3/flash/display/IBitmapDrawable.as";
include "as3/flash/display/IDrawCommand.as";
include "as3/flash/display/IGraphicsData.as";
include "as3/flash/display/IGraphicsFill.as";
include "as3/flash/display/IGraphicsPath.as";
include "as3/flash/display/IGraphicsStroke.as";

include "as3/flash/display/ActionScriptVersion.as";
//AVM1Movie
//Bitmap
//BitmapData
//BitmapDataChannel
//BitmapEncodingColorSpace
//BlendMode
//CapsStyle
//ColorCorrection
//ColorCorrectionSupport
//DisplayObject
//DisplayObjectContainer
//FocusDirection    
//FrameLabel
//GradientType
//Graphics
//GraphicsBitmapFill
//GraphicsEndFill
//GraphicsGradientFill
//GraphicsPath
//GraphicsPathCommand
//GraphicsPathWinding
//GraphicsShaderFill
//GraphicsSolidFill
//GraphicsStroke
//GraphicsTrianglePath
//InteractiveObject
//InterpolationMethod
//JointStyle
//JPEGEncoderOptions
//JPEGXREncoderOptions
//LineScaleMode
//Loader
//LoaderInfo
//MorphShape
//MovieClip
//NativeMenu    
//NativeMenuItem    
//NativeWindow    
//NativeWindowDisplayState    
//NativeWindowInitOptions    
//NativeWindowRenderMode    
//NativeWindowResize    
//NativeWindowSystemChrome    
//NativeWindowType    
include "as3/flash/display/PixelSnapping.as";
include "as3/flash/display/PNGEncoderOptions.as";
include "as3/flash/display/Scene.as";
//Screen    
//Shader
//ShaderData
//ShaderInput
//ShaderJob
//ShaderParameter
//ShaderParameterType
//ShaderPrecision
//Shape
//SimpleButton
//SpreadMethod
//Sprite
//Stage
//Stage3D
include "as3/flash/display/StageAlign.as";
include "as3/flash/display/StageAspectRatio.as";
include "as3/flash/display/StageDisplayState.as";
include "as3/flash/display/StageOrientation.as";
include "as3/flash/display/StageQuality.as";
include "as3/flash/display/StageScaleMode.as";
include "as3/flash/display/SWFVersion.as";
include "as3/flash/display/TriangleCulling.as";


//-- flash.display3D --
//Context3D
//Context3DBlendFactor
//Context3DClearMask
//Context3DCompareMode
//Context3DMipFilter
//Context3DProfile
//Context3DProgramType
//Context3DRenderMode
//Context3DStencilAction
//Context3DTextureFilter
//Context3DTextureFormat
//Context3DTriangleFace
//Context3DVertexBufferFormat
//Context3DWrapMode
//IndexBuffer3D
//Program3D
//VertexBuffer3D


//-- flash.display3D.textures --
//CubeTexture
//RectangleTexture
//Texture
//TextureBase


//-- flash.errors --
//flash.errors.IOError -- defined in flash_errors_classes.as
//flash.errors.EOFError -- defined in flash_errors_classes.as
//flash.errors.MemoryError -- defined in flash_errors_classes.as
//flash.errors.IllegalOperationError -- defined in flash_errors_classes.as
include "as3/flash/errors/ScriptTimeoutError.as";
include "as3/flash/errors/StackOverflowError.as";
include "as3/flash/errors/InvalidSWFError.as";
include "as3/flash/errors/SQLErrorOperation.as";
include "as3/flash/errors/SQLError.as";
include "as3/flash/errors/DRMManagerError.as";


//-- flash.events --
/* alpha */ include "as3/flash/events/IEventDispatcher.as";

//AccelerometerEvent
//ActivityEvent
//AsyncErrorEvent
//BrowserInvokeEvent
//ContextMenuEvent
//DataEvent
//DatagramSocketDataEvent
//DNSResolverEvent
//DRMAuthenticateEvent
//DRMAuthenticationCompleteEvent
//DRMAuthenticationErrorEvent
//DRMDeviceGroupErrorEvent
//DRMDeviceGroupEvent
//DRMErrorEvent
//DRMMetadataEvent
//DRMReturnVoucherCompleteEvent
//DRMReturnVoucherErrorEvent
//DRMStatusEvent
//ErrorEvent
/* alpha */ include "as3/flash/events/Event.as";
/* alpha */ include "as3/flash/events/EventDispatcher.as";
//EventPhase
//FileListEvent
//FocusEvent
//FullScreenEvent
//GameInputEvent
//GeolocationEvent
//GestureEvent
//GesturePhase
//HTMLUncaughtScriptExceptionEvent
/* alpha */ include "as3/flash/events/HTTPStatusEvent.as";
//IMEEvent
//InvokeEvent
//IOErrorEvent
//KeyboardEvent
//LocationChangeEvent
//MediaEvent
//MouseEvent
//NativeDragEvent
//NativeProcessExitEvent
//NativeWindowBoundsEvent
//NativeWindowDisplayStateEvent
//NetDataEvent
//NetMonitorEvent
//NetStatusEvent
//OutputProgressEvent
//PressAndTapGestureEvent
//ProgressEvent
//RemoteNotificationEvent
//SampleDataEvent
//ScreenMouseEvent
//SecurityErrorEvent
//ServerSocketConnectEvent
//ShaderEvent
//SoftKeyboardEvent
//SoftKeyboardTrigger
//SQLErrorEvent
//SQLEvent
//SQLUpdateEvent
//StageOrientationEvent
//StageVideoAvailabilityEvent
//StageVideoEvent
//StatusEvent
//StorageVolumeChangeEvent
//SyncEvent
//TextEvent
//ThrottleEvent
//ThrottleType
/* alpha */ include "as3/flash/events/TimerEvent.as";
//TouchEvent
//TouchEventIntent
//TransformGestureEvent
//UncaughtErrorEvent
//UncaughtErrorEvents
//VideoEvent


//-- flash.external --
//ExtensionContext
//ExternalInterface


//-- flash.filesystem --
//File
//FileMode
//FileStream
//StorageVolume
//StorageVolumeInfo


//-- flash.filters --
//BevelFilter
//BitmapFilter
//BitmapFilterQuality
//BitmapFilterType
//BlurFilter
//ColorMatrixFilter
//ConvolutionFilter
//DisplacementMapFilter
//DisplacementMapFilterMode
//DropShadowFilter
//GlowFilter
//GradientBevelFilter
//GradientGlowFilter
//ShaderFilter


//-- flash.geom --
//ColorTransform
//Matrix
//Matrix3D
include "as3/flash/geom/Orientation3D.as";
//PerspectiveProjection
include "as3/flash/geom/Point.as";
include "as3/flash/geom/Rectangle.as";
//Transform
//Utils3D
//Vector3D


//-- flash.globalization --
//Collator
//CollatorMode
//CurrencyFormatter
//CurrencyParseResult
//DateTimeFormatter
//DateTimeNameContext
//DateTimeNameStyle
//DateTimeStyle
//LastOperationStatus
//LocaleID
//NationalDigitsType
//NumberFormatter
//NumberParseResult
//StringTools


//-- flash.html --
//HTMLHistoryItem
//HTMLHost
//HTMLLoader
//HTMLPDFCapability
//HTMLSWFCapability
//HTMLWindowCreateOptions


//-- flash.media --
//scanHardware()

//AudioDecoder
//AudioPlaybackMode
//Camera
//CameraPosition
//CameraRoll
//CameraRollBrowseOptions
//CameraUI
//H264Level
//H264Profile
//H264VideoStreamSettings
//ID3Info
//MediaPromise
//MediaType
//Microphone
//MicrophoneEnhancedMode
//MicrophoneEnhancedOptions
//Sound
//SoundChannel
//SoundCodec
//SoundLoaderContext
//SoundMixer
//SoundTransform
//StageVideo
//StageVideoAvailability
//StageVideoAvailabilityReason
//StageWebView
//Video
//VideoCodec
//VideoStatus
//VideoStreamSettings


//-- flash.net --
//flash.net.getClassByAlias() -- defined in flash_net_classes.as
//navigateToURL()
//flash.net.registerClassAlias() -- defined in flash_net_classes.as
//sendToURL()

//flash.net.IDynamicPropertyOutput -- defined in IDynamicPropertyOutput.as
//flash.net.IDynamicPropertyWriter -- defined in IDynamicPropertyWriter.as
//flash.net.DynamicPropertyOutput -- defined in DynamicPropertyOutput.as

//DatagramSocket
//FileFilter
//FileReference
//FileReferenceList
//GroupSpecifier
//InterfaceAddress
//IPVersion
//LocalConnection
//NetConnection
//NetGroup
//NetGroupInfo
//NetGroupReceiveMode
//NetGroupReplicationStrategy
//NetGroupSendMode
//NetGroupSendResult
//NetMonitor
//NetStream
//NetStreamAppendBytesAction
//NetStreamInfo
//NetStreamMulticastInfo
//NetStreamPlayOptions
//NetStreamPlayTransitions
//NetworkInfo
//NetworkInterface
//flash.net.ObjectEncoding -- defined in ObjectEncoding.as
//Responder
//SecureSocket
//ServerSocket
//SharedObject
//SharedObjectFlushStatus
//Socket
//URLLoader
//URLLoaderDataFormat
//URLRequest
//URLRequestDefaults
include "as3/flash/net/URLRequestHeader.as";
//URLRequestMethod
//URLStream
//URLVariables
//XMLSocket


//-- flash.net.dns --
//AAAARecord
//ARecord
//DNSResolver
//MXRecord
//PTRRecord
//ResourceRecord
//SRVRecord


//-- flash.net.drm --
//AuthenticationMethod
//DRMContentData
//DRMDeviceGroup
//DRMManager
//DRMPlaybackTimeWindow
//DRMVoucher
//LoadVoucherSetting
//VoucherAccessInfo


//-- flash.notifications --
//NotificationStyle
//RemoteNotifier
//RemoteNotifierSubscribeOptions


//-- flash.printing --
//PaperSize
//PrintJob
//PrintJobOptions
//PrintJobOrientation
//PrintMethod
//PrintUIOptions


//-- flash.profiler --
//showRedrawRegions()

//Telemetry


//-- flash.sampler --
include "extensions/Sampler.as";
	//flash.sampler.StackFrame
	//flash.sampler.Sample
	//flash.sampler.NewObjectSample
	//flash.sampler.DeleteObjectSample
	//flash.sampler.clearSamples()
	//flash.sampler.startSampling()
	//flash.sampler.stopSampling()
	//flash.sampler.pauseSampling()
	//flash.sampler.sampleInternalAllocs()
	//flash.sampler.setSamplerCallback()
	//flash.sampler.getSize()
	//flash.sampler.getMemberNames()
	//flash.sampler.getSamples()
	//flash.sampler.getSampleCount()
	//flash.sampler.getInvocationCount()
	//flash.sampler.getSetterInvocationCount()
	//flash.sampler.getGetterInvocationCount()
	//flash.sampler.isGetterSetter()
	//flash.sampler.getLexicalScopes()
	//flash.sampler.getSavedThis()
	//flash.sampler.getMasterString()


//-- flash.security --
//IURIDereferencer
//CertificateStatus
//ReferencesValidationSetting
//RevocationCheckSettings
//SignatureStatus
//SignerTrustSettings
//X500DistinguishedName
//X509Certificate
//XMLSignatureValidator


//-- flash.sensors --
//Accelerometer
//Geolocation


//-- flash.system --
//fscommand()

//ApplicationDomain
include "as3/flash/system/Capabilities.as";
//ImageDecodingPolicy
//IME
//IMEConversionMode
//JPEGLoaderContext
//LoaderContext
//MessageChannel
//MessageChannelState
//Security
//SecurityDomain
//SecurityPanel
include "as3/flash/system/System.as";
//SystemUpdater
//SystemUpdaterType
//TouchScreenType
include "as3/flash/system/WorkerState.as";
include "as3/flash/system/Worker.as";
include "as3/flash/system/WorkerEvent.as";
include "as3/flash/system/WorkerDomain.as";


//-- flash.text --
//-- flash.text.engine --
//-- flash.text.ime --

//-- flash.trace --
include "extensions/Trace.as";
   //flash.trace.Trace

//-- flash.ui --
//ContextMenu
//ContextMenuBuiltInItems
//ContextMenuClipboardItems
//ContextMenuItem
//GameInput
//GameInputControl
//GameInputDevice
//Keyboard
//KeyboardType
//KeyLocation
//Mouse
//MouseCursor
//MouseCursorData
//Multitouch
//MultitouchInputMode

//-- flash.utils --
//flash.utils.flash_proxy namespace -- defined in Proxy.as

include "as3/flash/utils/clearInterval.as";
include "as3/flash/utils/clearTimeout.as";
include "as3/flash/utils/describeType.as";
include "as3/flash/utils/escapeMultiByte.as";
include "as3/flash/utils/getDefinitionByName.as";
include "as3/flash/utils/getQualifiedClassName.as";
include "as3/flash/utils/getQualifiedSuperclassName.as";
include "as3/flash/utils/getTimer.as";
include "as3/flash/utils/setInterval.as";
include "as3/flash/utils/setTimeout.as";
include "as3/flash/utils/unescapeMultiByte.as";

//flash.utils.IDataInput -- defined in IDataInput.as
//flash.utils.IDataInput2 -- defined in IDataInput.as
//flash.utils.IDataOutput -- defined in IDataOutput.as
//flash.utils.IDataOutput2 -- defined in IDataOutput.as
//flash.utils.IExternalizable -- defined in IExternalizable.as

//flash.utils.ByteArray -- defined in ByteArray.as
//flash.utils.CompressionAlgorithm -- defined in ByteArray.as
//flash.utils.Dictionary -- defined in Dictionary.as
include "as3/flash/utils/Endian.as";
//flash.utils.ObjectInput -- defined in ObjectInput.as
//flash.utils.ObjectOutput -- defined in ObjectOutput.as
//flash.utils.Proxy -- defined in Proxy.as
/* alpha */ include "as3/flash/utils/Timer.as";


//-- flash.xml --
//XMLDocument
//XMLNode
//XMLNodeType


